---
# handlers file for common
- name: Restart systemd-networkd
  become: true
  ansible.builtin.systemd:
   name: systemd-networkd
   state: restarted

- name: Restart systemd-resolved
  become: true
  ansible.builtin.systemd:
   name: systemd-resolved
   state: restarted
