---
# tasks file for common
- name: Create token
  ansible.builtin.set_fact:
    token: "{{ lookup('community.general.random_string', length=40, special=false) }}"
  run_once: true

- name: Elect control plane leader
  ansible.builtin.set_fact:
    cp_leader_name: "{{ groups['rke2_servers'][0] | split('.') | first }}"
  run_once: true

- name: Create config dir
  become: true
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'

- name: Create systemd-journald config dir
  become: true
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory
    mode: '0755'

# Will keep forever otherwise as there are not enough services to trigger rotation often
- name: Limit log retention
  become: true
  # Unfortunately, no restarting systemd-journald does not have the desired effect
  # See https://unix.stackexchange.com/a/379531
  notify: Reboot
  ansible.builtin.template:
    src: rke2-journald.conf.j2
    dest: /etc/systemd/journald.conf.d/00-rke2.conf
    owner: root
    group: root
    mode: '0640'

- name: Check if rke2 installed
  ansible.builtin.stat:
    path: /usr/local/bin/rke2
  register: rke2_stat_result

- name: Get rke2 installer script
  when: not rke2_stat_result.stat.exists
  ansible.builtin.get_url:
    url: https://get.rke2.io
    dest: /tmp/rke2-install.sh
    mode: '0755'
