---
# tasks file for post
- name: Fix kubeconfig
  ansible.builtin.replace:
    path: "{{ lookup('env', 'HOME') }}/.kube/config"
    regexp: '127\.0\.0\.1'
    replace: "{{ vip_router_id }}.localdomain"

- name: Change kubeconfig perms
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.kube/config"
    mode: '0600'

- name: Print dashboard token grab
  ansible.builtin.debug:
    msg:
      - 'If you deployed the dashboard, run the following command to grab the bearer token:'
      - 'kubectl -n kubernetes-dashboard get secret $(kubectl -n kubernetes-dashboard get sa/admin-user -o jsonpath="{.secrets[0].name}") -o go-template="{{.data.token | base64decode}}"'
      - 'To access the dashboard, run kubectl proxy to start the proxy'
      - 'Then visit http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/'
